PR for code review
Cyber-Labs/NeuroEvolutionary-Self-Driving-Car pull request #1
Opened 2018-09-30 08:38 UTC by Samuelimza

Initial PR.

2018-10-04 11:57 UTC, AarushJ requested changes

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +class Car {
add access specifier

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +  float drag = 0.96;
use final if these are not to be used later

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +  void update() {
change name to update_car_state()

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +  boolean acc = false, left = false, right = false, decc = false;
acc -> acceleration

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +  boolean acc = false, left = false, right = false, decc = false;
decc -> deacceleration

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +  Car(int x, int y, int species) {
use final in parameters also if their value is not changing later.

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +    if (species == 1) {
use switch case here

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +      Marker current = markers.get(i);
current -> currentMarkerIndex

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +      if (myMap.pixels[index0] == -16777216 || myMap.pixels[index1] == -16777216 || myMap.pixels[index2] == -16777216 || myMap.pixels[index3] == -16777216) {
avoid magic numbers. Store such values in variables and then use those variables everywhere needed .

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +
remove this line

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +  void show() {
change function name to something clear

2018-10-04 11:57 UTC, AarushJ commented on GA2/Car.pde
> +      if (species == 1) {
switch case

2018-10-04 11:57 UTC, AarushJ commented on GA2/GA2.pde
> +  myMap = loadImage("data/tracks/track" + track + ".png");
Read about MessageFormat class and use message formatting here.

2018-10-04 11:57 UTC, AarushJ commented on GA2/GA2.pde
> +  LeftView = loadImage("data/LeftView.png");
constant here for string

2018-10-04 11:57 UTC, AarushJ commented on GA2/GA2.pde
> +  loadMarkers("D:/NewFolder/Osama/Programming/Java/Processing/GA2/data");
constant here for string

2018-10-04 11:57 UTC, AarushJ commented on GA2/GA2.pde
> +    text("Gen: " + ga.generation, 0, 0);
use message formattter here also

2018-10-04 11:57 UTC, AarushJ commented on GA2/GA2.pde
> +  JSONArray markersArray = loadJSONArray(path + "/markers1.json");
use Message formatter here also

2018-10-04 11:57 UTC, AarushJ commented on GA2/GeneticAlgorithm.pde
> +        maxFitI = i;
change to maxFitnessIndex

2018-10-04 11:57 UTC, AarushJ commented on GA2/GeneticAlgorithm.pde
> +    for (int i = 0; i < cars.length; i++) {
make separate method for calculating max and max index (follow Single Responsibility Principle)

2018-10-04 11:57 UTC, AarushJ commented on GA2/GeneticAlgorithm.pde
> +    JSONObject metaData = new JSONObject();
create separate method for metadata generation.

2018-10-04 11:57 UTC, AarushJ commented on GA2/GeneticAlgorithm.pde
> +    saveJSONArray(generationArray, "generations/metaDataGens/" + saveName + ".json");
Use message formatter here

2018-10-04 11:57 UTC, AarushJ commented on GA2/GeneticAlgorithm.pde
> +    JSONArray generationArray = loadJSONArray("generations/metaDataGens/" + generationToLoad + ".json");
Use message formatter here

2018-10-04 11:57 UTC, AarushJ commented on GA2/GeneticAlgorithm.pde
> +    catch(Exception exception) {
1. Avoid generic exception. Write exact exception. 
2. If there are multiple exceptions which u think my occur, use multiple catch statements with the single try block above. 
3. Learn to use logs . See @Slf4j annotation of lombok.

2018-10-04 11:57 UTC, AarushJ commented on GA2/Markers.pde
> +class Marker{
@AllArgsConstructor or something similar in lombok. use it here.

2018-10-04 11:57 UTC, AarushJ commented on GA2/NNetwork.pde
> +  int[] architecture = {3, 5, 4, 4};
change architecture to a more obvious name

2018-10-05 12:54 UTC, Samuelimza commented on GA2/Car.pde
> +  float drag = 0.96;
while loading a save, they need to be changed, hence cannot be set final.

2018-10-05 13:12 UTC, Samuelimza commented on GA2/Car.pde
> +  void update() {
Done.

2018-10-05 13:12 UTC, Samuelimza commented on GA2/Car.pde
> +  boolean acc = false, left = false, right = false, decc = false;
Done.

2018-10-05 13:12 UTC, Samuelimza commented on GA2/Car.pde
> +  Car(int x, int y, int species) {
Done.

2018-10-05 13:12 UTC, Samuelimza commented on GA2/Car.pde
> +    if (species == 1) {
Done.

2018-10-05 13:12 UTC, Samuelimza commented on GA2/Car.pde
> +      Marker current = markers.get(i);
Done.

2018-10-05 13:12 UTC, Samuelimza commented on GA2/Car.pde
> +
Done.

2018-10-05 13:12 UTC, Samuelimza commented on GA2/Car.pde
> +      if (myMap.pixels[index0] == -16777216 || myMap.pixels[index1] == -16777216 || myMap.pixels[index2] == -16777216 || myMap.pixels[index3] == -16777216) {
Done.

2018-10-05 13:13 UTC, Samuelimza commented on GA2/Car.pde
> +  void show() {
Done.

2018-10-05 13:13 UTC, Samuelimza commented on GA2/Car.pde
> +      if (species == 1) {
Done.

2018-10-05 13:13 UTC, Samuelimza commented on GA2/GA2.pde
> +  LeftView = loadImage("data/LeftView.png");
Done.

2018-10-05 13:13 UTC, Samuelimza commented on GA2/GA2.pde
> +  loadMarkers("D:/NewFolder/Osama/Programming/Java/Processing/GA2/data");
Done.

2018-10-05 13:14 UTC, Samuelimza commented on GA2/GeneticAlgorithm.pde
> +        maxFitI = i;
Done.

2018-10-05 15:46 UTC, Samuelimza commented on GA2/GeneticAlgorithm.pde
> +    for (int i = 0; i < cars.length; i++) {
Done.

2018-10-05 21:58 UTC, Samuelimza commented on GA2/GeneticAlgorithm.pde
> +    JSONObject metaData = new JSONObject();
Done.

2018-10-05 22:02 UTC, Samuelimza commented on GA2/NNetwork.pde
> +  int[] architecture = {3, 5, 4, 4};
Done.

2018-10-05 22:03 UTC, Samuelimza commented on GA2/Car.pde
> +class Car {
Done.

2018-10-06 11:52 UTC, Samuelimza commented on GA2/GA2.pde
> +  myMap = loadImage("data/tracks/track" + track + ".png");
Done.

2018-10-06 12:14 UTC, Samuelimza commented on GA2/GA2.pde
> +    text("Gen: " + ga.generation, 0, 0);
Done.

2018-10-06 12:16 UTC, Samuelimza commented on GA2/GA2.pde
> +  JSONArray markersArray = loadJSONArray(path + "/markers1.json");
Path was constant hence set as final instead.

2018-10-06 12:34 UTC, Samuelimza commented on GA2/GeneticAlgorithm.pde
> +    JSONArray generationArray = loadJSONArray("generations/metaDataGens/" + generationToLoad + ".json");
Done.

2018-10-06 12:38 UTC, Samuelimza commented on GA2/GeneticAlgorithm.pde
> +    saveJSONArray(generationArray, "generations/metaDataGens/" + saveName + ".json");
Done.

2018-10-06 14:42 UTC, Samuelimza commented on GA2/GeneticAlgorithm.pde
> +    catch(Exception exception) {
Done 1, 2.
Looking into 3.

2018-10-11 17:52 UTC, merged